### PR TITLE
Fix indentation mistake

### PR DESCRIPTION
**Pull request by JWijkhuizen**
No fd that meet the nfr's could be found due to this mistake.

### CODE REVIEW

**Comment by chcorbato** [comment]
> No fd that meet the nfr's could be found due to this mistake.

@JWijkhuizen can you report here how to replicate this behavior you mention?
Is it running one of the tests?

**Comment by JWijkhuizen** [comment]
No not with the tests of  reasoner.

It can be replicated with a simulation where adaptation is required.
For example using the example from the readme in `rosin-project/metacontrol_experiments`:
`./run_single_sim.sh -i 1 -g 1 -n "f1_v2_r2" -o 2 -r "true" -p 1.7 -c "false"`

**Review by chcorbato — COMMENTED** [review]
I see the issue with the logic.
However, I see also another problem:
The break statement in the `if` conditions were intended to skip the last statement in the outer for loop adding the `fd` whose `qas` comply with with the `nfr`s to the `filtered` list of FD that meet the NFRs.
Those `break`s should be `continue` statements, but apply to the outer loop.
I think fixing this logic requires a separate branch.

**Comment by Rezenders** [comment]
@chcorbato can this PR be closed?

**Comment by chcorbato** [comment]
> @chcorbato can this PR be closed?

I have not looked back into the status of the code. Have you checked the issues I pointed to [above](https://github.com/meta-control/mc_mros_reasoner/pull/108#pullrequestreview-499286026)?

**Comment by Rezenders** [comment]
I am closing this. I don't think this PR applies anymore.

**Pull request closed without merging**
